### ISSUE TITLE
Support help_text in filter forms

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/design-system#149]
Some filter elements are form fields (see #148). 

For these fields, we should support `small` for help text, as per other form elements. 

At the moment `small` elements in a filter are styled in the same way as other text (all caps, same font-size).

Adding:

```css
.ds-filter form small {
  text-transform: initial;
  font-size: $ss7;
}
```

Makes the small tag look the same as other forms.
