### ISSUE TITLE
Links in status messages are 🤢

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/design-system#37]
![Screenshot from 2022-01-10 18-12-36](https://user-images.githubusercontent.com/242329/148817342-4718058a-e4d9-41bd-9448-ee2af2ed267f.png)
Can be fixed with 

```scss
.ds-status-message a {
  color: $white;
}
```
![Screenshot from 2022-01-10 18-14-53](https://user-images.githubusercontent.com/242329/148817512-23994686-aa39-45b2-b322-cea0f61eeb76.png)
